port: ":8080"

router:
  routes:
    - path: "/users"
      service-name: "user-service"
      methods:
        - GET
        - POST
      middleware:
        - auth
        - logging

    - path: "/products"
      service-name: "product-service"
      methods:
        - GET
      middleware:
        - logging

service-registry:
  services:
    - name: "user-service"
      urls:
        - "http://localhost:9091"
        - "http://localhost:9092"
    - name: "product-service"
      urls:
        - "http://localhost:9093"
        - "http://localhost:9094"