services:
  - name: users
    urls:
      - http://localhost:9001
      - http://localhost:9002
  - name: products
    urls:
      - http://localhost:9003
      - http://localhost:9004

routes:
  - path: /api/users
    service: users
    # middleware:
    #   - auth
    #   - log
  - path: /api/products
    service: products
    # middleware:
    #   - log